server:
  port: 8080
  servlet:
    context-path: /api
---
#spring:
 # jpa:
  #  database: POSTGRESQL
   # show-sql: true
    #hibernate:
     # ddl-auto: create-drop
  #datasource:
   # platform: postgres
    #url: jdbc:postgresql://trainingdb.cw68wpyuzfqr.us-east-1.rds.amazonaws.com/postgres
    #username: michaelpetillo
    #password: steelers
    #driverClassName: org.postgresql.Driver
#use env variables for sensitive info